### ISSUE TITLE
Need to report error if index names are not unique

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#1082]
**Is your feature request related to a problem? Please describe.**

All index names within a Postgres database have to be unique. Serverpod does not warn the user currently when index names are accidentally reused. This causes .pgsql files to be created that cannot be loaded into the server.

**Describe the solution you'd like**

`serverpod generate` needs to stop with an error if index names are not unique.

**Comment by vlidholt** [comment]
@Isakdl, maybe this is a rather easy addition to what you are working on with the analyzer now?

**Comment by Isakdl** [comment]
@lukehutch do you mean globally across several Protocol files? In a single protocol file this should already be reported as an error since it is even invalid yaml to specify the same key twice.

@vlidholt Yeah it shouldn't be too hard now with the new analyzer since we now support resolving dependencies between files.

**Comment by Isakdl** [comment]
@lukehutch Agreed, I would like to add a unique key on the fields in the future that automatically would create an index, i.e:

```yaml
class: Example
fields:
  name: String, unique
```
With that said reporting an error is a good idea anyway, and until we have the unique key this fix will be helpful for this case as well.
