### ISSUE TITLE
"serverpod_runtime_settings" does not exist 

### ISSUE THREAD

**Issue by Dev-Arnab-Flutter** [serverpod/serverpod#1278]
**Describe the bug**
Failed to connect to the database. Retrying in 10 seconds. PostgreSQLSeverity.error 42P01: relation "serverpod_runtime_settings" does not exist 

**Expected behavior**
The server should up and running

**Screenshots**
![image_2023-08-13_191507218](https://github.com/serverpod/serverpod/assets/54588215/0ac09586-cc93-4775-b6f0-7e8dcd72dc07)

**Serverpod versions**
Serverpod version: 1.1.1
 - _Library version:_ Check the pubspec.yaml file for the version of Serverpod you are using.
![image_2023-08-13_191606005](https://github.com/serverpod/serverpod/assets/54588215/2011b36f-d0a9-4071-856e-ac0f9bf582fe)

**Platform information**
Windows 10 pro 64 bitbuild 19045

How to solve that part???

**Comment by Isakdl** [comment]
This is because you haven't created the tables in the database!

You have to run the script `setup-tables.cmd` that you have in your root folder of the project. You can also do this manually like described here: https://stackoverflow.com/questions/76180598/serverpod-sql-error-when-starting-a-clean-project/76180599#76180599.
