### ISSUE TITLE
error in google authentication

### ISSUE THREAD

**Issue by dongri727** [serverpod/serverpod#1532]
Authentication is being implemented.
E-mail worked well.　I can authenticate, take an Id, and tie it to Data.
I have set up Google Authentication with reference to medium, but I get the following error
I get the following error.
What should I fix?
<img width="403" alt="authentication error" src="https://github.com/serverpod/serverpod/assets/84567162/53303682-03ef-42b1-9ac6-664f280bdc7d">

Info.plist is already set up as follows.
<img width="304" alt="info-plist" src="https://github.com/serverpod/serverpod/assets/84567162/8cc0c54f-ba02-4421-8d12-c1d1c8c5ba39">

[✓] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale ja)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.84.0)
[✓] Connected device (2 available)
[✓] Network resources

Also, is the following warning displayed in dart bin/main.dart relevant?

../../../.pub-cache/hosted/pub.dev/x509-0.2.4/lib/src/extension.dart:45:48: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
      ASN1Parser(sequence.elements[octetIndex].contentBytes()!).nextObject(),

**Comment by dongri727** [comment]
```dart
dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: ^1.1.1
  acorn_client:
    path: ../acorn_client

  serverpod_auth_shared_flutter: ^1.1.1
  serverpod_auth_email_flutter: ^1.1.1
  serverpod_auth_google_flutter: ^1.1.1
  serverpod_auth_apple_flutter: ^1.1.1
```

**Comment by flutterindiadev** [comment]
I guess you are following this article to integrate google sign in
https://medium.com/serverpod/integrating-google-sign-in-with-serverpod-authentication-part-2-6fade3099baf

**Comment by Isakdl** [comment]
If I'm not mistaken I think the name of the `GoogleService-Info.plist` file is important. You have named it with an underscore `_` instead of a dash `-`. Try to change the name of the file.

**Comment by flutterindiadev** [comment]
You are right @Isakdl but that shouldn't be the issue in case of web, as I am facing this error on web

**Comment by dongri727** [comment]
Thanks for the suggesstion.

Not only did I superficially rename the file,
I have deleted the file and re-installed it,
Unfortunately, I get the same Error.

flutter: serverpod_auth_google: GoogleSignIn
flutter: serverpod_auth_google: Signing out from google
flutter: Failed call: serverpod_auth.google.authenticateWithServerAuthCode
flutter: ServerpodClientException: Internal server error. Call log id: 156, statusCode = 500
flutter: serverpod_auth_google: ServerpodClientException: Internal server error. Call log id: 156, statusCode = 500
flutter: #0      ServerpodClient.callServerEndpoint (package:serverpod_client/src/serverpod_client_io.dart:82:9)
<asynchronous suspension>
#1      signInWithGoogle (package:serverpod_auth_google_flutter/src/auth.dart:66:24)
<asynchronous suspension>

https://github.com/serverpod/serverpod/assets/84567162/4c49729a-9bf9-4946-83ab-7ee9e0be24c6
<img width="305" alt="スクリーンショット 2023-11-18 12 25 39" src="https://github.com/serverpod/serverpod/assets/84567162/5a47d447-be41-4870-ac9b-4bd5739d7d6e">

<img width="396" alt="スクリーンショット 2023-11-18 12 26 00" src="https://github.com/serverpod/serverpod/assets/84567162/809f34c8-3adf-4d84-a38d-1c0abcb2910d">

**Comment by flutterindiadev** [comment]
Is there any update here? this issue still persists.

**Comment by Isakdl** [comment]
I just took a look at the crash, we need to have a better error message here, but the reason is that the *server* is not loading the secret credentials. 

Have you put the serverside config file in your server project?

The server credentials need to be put into the `config` folder, and has to be named `google_client_secret.json`. 

[Instructions from our medium article](https://medium.com/serverpod/integrating-google-sign-in-with-serverpod-authentication-part-2-6fade3099baf):

[In the Google Cloud console](https://console.cloud.google.com)

**Create Credentials**: Navigate to ‘Credentials’ under ‘APIs & Services’. Click ‘Create Credentials’ and select ‘OAuth client ID’. Configure the OAuth client as a ‘Web application’. Name your client and leave the Authorized JavaScript origins and Authorized redirect URIs fields blank for now.

**Obtain the JSON credentials**: After creating the credentials, you’ll be provided with an option to download the secrets as a JSON. Click the “DOWNLOAD JSON” button. Rename the file to `google_client_secret.json`.

**Add secret to Serverpod**: Move the secret file into your server project and put it under `config/google_client_secret.json`. Serverpod will by default look for this file to interact with Google.

**Comment by luisgustavoo** [comment]
@Isakdl  I'm following the tutorial above and I'm still getting this error. I believe all the settings are correct, as shown in the screenshots below:


<img width="1172" height="516" alt="Image" src="https://github.com/user-attachments/assets/9cb08d70-7ab9-4059-8216-7a67e9e22c9f" />

<img width="2694" height="1574" alt="Image" src="https://github.com/user-attachments/assets/a0f5fc78-0888-4158-b0d1-d6de29762fc2" />

<img width="672" height="466" alt="Image" src="https://github.com/user-attachments/assets/639595b4-5fce-46da-bdce-c4e9a644a62a" />

<img width="600" height="448" alt="Image" src="https://github.com/user-attachments/assets/9ddb36d2-a05f-4100-b175-7094a472a31e" />

**Comment by luisgustavoo** [comment]
Any news on this issue?
