### ISSUE TITLE
Database migrations (epic)

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#154]
Add built-in support for handling database migrations. (This ticket needs to be fleshed out.)

### Tasks for 1.2
- [ ] #1117 
- [x] #1116
- [x] #1499 
- [x] #1500 
- [x] #1501 
- [x] #1502 
- [x] #1504 
- [x] #1505
- [x] #1402 
- [x] #1318 
- [x] #1512 

### Future tasks
- [ ] #1446 
- [x] #1503

**Comment by fischerscode** [comment]
Three ideas:
- add new tables, columns (requires #236) and indices automatically
- delete deleted indices automatically
- allow the developer to provide pgsql files used to update from one database version to an other

Of course it would be cool if everything would happen automatically, but in my opinion this would be a nice and manageable first step.

**Comment by Tienisto** [comment]
Most of my Spring Boot projects are using Flyway for database migration. After using JPA/Hibernate for a while I think that being explicit is more important. Data is too important to leave the framwork doing black magic :) Just my 2 cents.

**Comment by vlidholt** [comment]
@xioxin Thanks, will definitely have a look there!

**Comment by chimon2000** [comment]
Another potential reference: Stormberry is an ORM that supports migrations: https://pub.dev/packages/stormberry

**Comment by hytdsh** [comment]
I would like to check the status of the DB migration feature.
Is there any publicly available forks or branches?

**Comment by vlidholt** [comment]
Not yet, we are focusing on getting the deployments to GCP done first, then database migrations are next on the list!

**Comment by blopker** [comment]
Another solution is [Dbmate](https://github.com/amacneil/dbmate). Written in go, so it could be shipped a Dart package. They have it on npm for example: https://www.npmjs.com/package/dbmate. Serverpod would still have to figure out how to generate the SQL diffs though.

**Comment by kieran-novarca** [comment]
Just wanted to say that we are using Serverpod in production on a large application and migrations are the second most requested feature from our dev team next to inheritance.

This would solve a lot of issues we have, especially if there was some sort of auto-migrate CLI script that once you pull new changes from a repo you could run the script to automatically update your db. It would be great if you could also run this script to first create the database as well rather than having to manually copy the PGSQL code into a db manager if it just used the existing connection info within serverpod to automatically run the queries on the db. 

If you put a timestamp in the name of the migration file instead of a version number, this should fix any issues where two devs working on the same project both make changes to the db and therefore create a migration file and then merge their changes together. The timestamp should put the migrations in the correct order within the migrations folder so that they run in the correct order.

**Comment by blopker** [comment]
I've been playing with https://github.com/odroe/prisma-dart. It builds on a mature database management solution from the node world. I wonder if there's anything to learn from it for this?

**Comment by vikas-flutter** [comment]
> 

Hi. Wanted to understand few things
1) What use cases you have for db migration to be required?
2) What is the first most requested feature?

**Comment by vikas-flutter** [comment]
> Just wanted to say that we are using Serverpod in production on a large application and migrations are the second most requested feature from our dev team next to inheritance.
> 
> This would solve a lot of issues we have, especially if there was some sort of auto-migrate CLI script that once you pull new changes from a repo you could run the script to automatically update your db. It would be great if you could also run this script to first create the database as well rather than having to manually copy the PGSQL code into a db manager if it just used the existing connection info within serverpod to automatically run the queries on the db.
> 
> If you put a timestamp in the name of the migration file instead of a version number, this should fix any issues where two devs working on the same project both make changes to the db and therefore create a migration file and then merge their changes together. The timestamp should put the migrations in the correct order within the migrations folder so that they run in the correct order.

Hi. Wanted to understand few things

What use cases you have for db migration to be required?
What is the first most requested feature?
