### ISSUE TITLE
RFC: Serverpod Mini

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#1725]
This document outlines the new Serverpod Mini feature. Serverpod Mini is Serverpod without database and configuration files. The purpose is to make Serverpod more accessible for developers who just want to try it out, or who do not want to use the database. There can be various reasons for this, like using some other backend for data, or just doing simple data processing.

![serverpod-mini](https://github.com/serverpod/serverpod/assets/1539812/701c1056-ecd0-4f04-a4a4-2446f23bff1e)

### Serverpod create
New serverpod create command:
```bash
serverpod create --template mini mypod
```

Or shortcut:
```bash
serverpod create --mini mypod
```

Upgrade from mini to full version:
```bash
serverpod create --template server .
```

### Excluded files
Mini comes with the configuration files excluded:

```
.gcloudignore
Dockerfile
config/
deploy/
docker-compose.yaml
web/
```

### Detecting Mini mode
If the config/ directory is missing, Serverpod starts in Mini mode.

### Disabled features
In Mini mode, the following features are disabled:

- Database connections
- Logging
- Future calls
- Insights
- Web server
- Redis
- File uploads

### Implementation
Make an enum that contains the flavor Serverpod is using (Mini/full) and set it at startup. Make switches for different parts and throw an exception when trying to access features that aren’t available in Mini. Logging goes straight to stdout/stderr. Make it possible to specify logging level as a paramber.

Print if we are using Mini at startup.

Add an option for setting the port of your Serverpod server through code. (This overrides any configuration files, if upgraded to full Serverpod.)

Generate warnings/errors for keywords used by database (e.g., `table` and `relation`). This applies to CLI and analyzer.

**Comment by vlidholt** [comment]
@AdamMusa, we may break out the database features at some point in the future (they are currently quite tightly coupled, so it would take some work).

**Comment by tylersavery** [comment]
This makes sense to me. Although having a DB (and the other features) is great for most apps, it's not always required. The real value of Serverpod is the client code generation between the server and flutter so you don't have to think about transforming data via a traditional API. 

And yeah, I think for getting traction the setup for this would be a lot less cumbersome since you don't have to teach anyone to setup a database.

All this being said, I don't know if I would ever use this TBH since pretty much anything I make requires a centralized persistent data store.

**Comment by dnsflnv** [comment]
How about making something like https://pocketbase.io/, with SQLite?

**Comment by princechaudhary874** [comment]
Nice

**Comment by mozexty** [comment]
@tylersavery
I see this move as a way to decouple Serverpod from the Postgres database, which could ease the adoption of other databases in the future.
In the past, there has been a discussion about the adoption of SurrealDB.

This might be the way to go.


On 9 Jan 2024, at 13:22, tylersavery ***@***.***> wrote:

﻿

This makes sense to me. Although having a DB (and the other features) is great for most apps, it's not always required. The real value of Serverpod is the client code generation between the server and flutter so you don't have to think about transforming data via a traditional API.

And yeah, I think for getting traction the setup for this would be a lot less cumbersome since you don't have to teach anyone to setup a database.

All this being said, I don't know if I would ever use this TBH since pretty much anything I make requires a centralized persistent data store.

**Comment by ps6067966** [comment]
Hi @vlidholt 
Instead of Serverpod mini, name "Serverpod Lite" make more sense.

**Comment by plakshay** [comment]
I was advised to contribute to Serverpod, and my beginner kit arrived in the form of a Serverpod Mini. 
Thank you!

**Comment by jason-downs** [comment]
There should be an easy way to downgrade an existing project to the "mini" version of it, removing the database functionality etc, assuming it's not being used in the project. The mini version of serverpod would be ideal for my use case where I'm using Supabase for everything but I would not be eager to start a brand new project and try to migrate the code over.

**Comment by bailyzheng** [comment]
Can serverpod mini server side run in flutter?

**Comment by dkbast** [comment]
Would it be possible to (selectively) enable some of the features which are disabled?

1. Database connections (optional sqlite backend)
2. Logging (depends on db?)
3. Future calls (depends on db?)
4. Insights (is a db interface?)
5. Web server <- this would be great if the serverpod mini is running as a simple dart web server, eg for accepting webhooks 
6. Redis (probably not needed)
7. File uploads (depends on db?)

Since most of the disabled features depend on the database, I see why they are disabled, but those are the features which make serverpod interesting over a simple shelf/dartfrog server - without these features the "only" big differentiator is the generated client, which is great, but feels like it's not "enough"?
