### ISSUE TITLE
Not compatible with aws email package

### ISSUE THREAD

**Issue by mike-novarca** [serverpod/serverpod#1794]
**Describe the bug**
Add package aws_sesv2_api to the server pub spec. This package requires uuid v3.0.3, Serverpod requires uuid v 4.0.0 versioning files

**To Reproduce**
Add package aws_sesv2_api to the server pub spec. This package requires uuid v3.0.3, Serverpod requires uuid v 4.0.0 versioning files

**Expected behavior**
No versioning conflict 

**Screenshots**

**Serverpod versions**
 -  _CLI Version:_1.2.
 - _Library version:_1.2

**Platform information**
On which platforms do you experience the issue. Please provide as much information here as you can. Where are you running the server, which front end device are you using?

**Additional context**

**Comment by Isakdl** [comment]
Hey @mike-novarca 

As Serverpod is using a newer version, the problem lies in the dependency you are trying to use. I would suggest making an issue of the repo of `aws_sesv2_api` and asking them to update it. Unfortunately, the older 3.0.0 version also causes other dependency incompatibilities and our policy is to support as wide a range of versions as possible. Still, in cases of incompatibility, we opt for keeping up with the updated dependencies. 

In the short term you have two solutions, either use the older Serverpod version, or make a fork of the other dependency and bump the version of uuid.
