### ISSUE TITLE
Composable Queries

### ISSUE THREAD

**Issue by craiglabenz** [serverpod/serverpod#2001]
**Is your feature request related to a problem? Please describe.**
Currently, queries feel cumbersome to build in server side functions with multiple optional parameters. Consider this endpoint which accepts two optional filters:

```dart
Future<List<Example>> get(Session session, {DateTime? createdAt, Set<int>? ids}) async {
  bool passedIds = ids != null && ids.isNotEmpty;
  if (createdAt == null && !passedIds) {
    return Example.db.find(session);
  } else if (createdAt != null && !passedIds) {
    return Example.db.find(session, where: (t) => t.createdAt > createdAt);  
  } else if (createdAt != null && passedIds) {
    return Example.db.find(session, where: (t) => t.createdAt > createdAt && t.id.inSet(ids);      
  }
  // throw 500 here?? - expected to never reach
}
```

And, of course, endpoints will realistically accept many possible filters.

**Describe the solution you'd like**
If, instead of returning a list of the model itself, methods like `find()` returned some sort of a composable `Query` object with an `evaluate()` or `run()` method, then the above function could look like this:

```dart
Future<List<Example>> get(Session session, {DateTime? createdAt, Set<int>? ids}) async {
  Query query = Example.db.find(session);
  if (createdAt != null) {
    query = query.where((t) => t.createdAt > createdAt);
  }
  if (ids != null && ids.isNotEmpty) {
    query = query.where((t) => t.id.inSet(ids));
  }
  return query.run();
}
```

**Describe alternatives you've considered**
One alternative is that something like this is already possible, and I am merely unaware of the right incantations :)

**Additional context**
Naturally, boolean logic would come into play here. Should a second `.where()` call always use AND logic with previous invocations? (My assumption is, Yes). But, an OR mechanism would need to exist as well.

**Comment by craiglabenz** [comment]
Upon investigation, it looks like a lot of these composable query mechanics exist inside the `SelectQueryBuilder` class, but do not seem to be exposed in the current public API.

**Comment by SandPod** [comment]
If I understand your use case correctly you would like to possibly append multiple query expressions depending on the input arguments.

Expressions are inherently composable, and since the `where` parameter of the `find(...)` method is just a simple callback that expects an `Expression` to be returned this should already be possible (although maybe not as elegant as your suggested solution).

Some intricate knowledge:
-  The `t` parameter in the `where` parameters callback is just the table definition for the table the query is placed towards.
- Under the hood we utilize something called a `WhereExpressionBuilder` as type, this can be defined by the user as well.

You could either define define the `Expression` completely outside of the where statement and return it:
```dart
uture<List<Example>> get(
  Session session, {
  DateTime? createdAt,
  Set<int>? ids,
}) async {
  var t = Example.t;
  final createdAtFilter = t.createdAt > createdAt;
  final idFilter = t.id.inSet(ids);

  Expression? query;
  if (createdAt != null) {
    query = query == null ? createdAtFilter : query & createdAtFilter;
  }

  if (ids != null && ids.isNotEmpty) {
    query = query == null ? idFilter : query & idFilter;
  }

  if (query == null) {
    // throw an error or use some default value
  }

  return Example.db.find(session, where: (_) => query!);
}
```

Or compose it as part of the where statement using the expression builder:
```dart
Future<List<Example>> get(
  Session session, {
  DateTime? createdAt,
  Set<int>? ids,
}) async {
  return Example.db.find(session, where: (t) {
    final createdAtFilter = t.createdAt > createdAt;
    final idFilter = t.id.inSet(ids);

    Expression? expression;
    if (createdAt != null) {
      expression =
          expression == null ? createdAtFilter : expression & createdAtFilter;
    }

    if (ids != null && ids.isNotEmpty) {
      expression = expression == null ? idFilter : expression & idFilter;
    }

    if (expression == null) {
      // throw an error or use some default value
    }

    return expression;
  });
}
```

> Upon investigation, it looks like a lot of these composable query mechanics exist inside the SelectQueryBuilder class, but do not seem to be exposed in the current public API.

The `SelectQueryBuilder` class is our internal SQL query builder, the reason we have not exposed it is because it is highly coupled with the structure of our models. So a lot of knowledge around the builder would be required to use it as a general query builder :) 

Possibly related feature: https://github.com/serverpod/serverpod/issues/1392

**Comment by craiglabenz** [comment]
Thanks, that's quite helpful! And yes, this problem is definitely in a similar vibe to #1392. Sadly, their "hundreds of columns" issue may render this particular solution only partially satisfying; but I think this gives me enough to work with :smile:
