### ISSUE TITLE
Need way to snapshot/restore database via Dart API, for unit testing

### ISSUE THREAD

**Issue by lukehutch** [serverpod/serverpod#2006]
**Is your feature request related to a problem? Please describe.**

I would like a Dart API for snapshotting and restoring Postgres databases, for the purposes of making unit tests work reliably. (Probably this should work for REDIS too, but I'm not currently using that.)

**Describe the solution you'd like**

I want to be able to start a unit test from a specific database snapshot every time it runs.

Ideally there would be a Dart API for running `pg_dump` and `pg_restore` on a Docker Postgres instance.

**Describe alternatives you've considered**

Blowing away the Docker instances and recreating them for every unit test, then re-initializing the database, would be very slow, not to mention that it can't be done directly in Dart, you have to run shell commands.

**Comment by SandPod** [comment]
Have you had a look at how we run our integration tests? Is that close to what you are after? If so, we could expose `IntegrationTestServer` with minimal effort and make it possible to run similar tests.

We opt for explicit database seeding through the generated models since that brings two major benefits:

1. It makes it clear what data is stored in the database using the same language as the application.
2. The seeding is tied to the models so it will evolve along with the application if the model is updated.

Example where we seed the database the same for all tests: https://github.com/serverpod/serverpod/blob/main/tests/serverpod_test_server/test_integration/column_operations/column_bool_test.dart

Example where we seed the database for each individual test: https://github.com/serverpod/serverpod/blob/main/tests/serverpod_test_server/test_integration/database_operations/entity_relations/one_to_many/find/where_any_test.dart

Ideally we wouldn't need to interact with a real database at all as that would allow us to run the tests concurrently. But this is a great way to validate that the read and writes proceed expected results.

**Comment by lukehutch** [comment]
I looked at the tests and could not figure out how it all worked. I'll try looking at it again tomorrow based on these pointers. 

However, I do want to point out that in my case, the database can't be mocked-out, because all my most important queries are unsafe/raw SQL queries.

This might be another usecase for #1719 though, since tests would run a lot faster if they could be run against SQLite rather than Postgres, if a lot of database setup and teardown is needed.

**Comment by lukehutch** [comment]
> 1. It makes it clear what data is stored in the database using the same language as the application.

Also, to this point specifically: this is the reason I also requested #1009: I want to be able to call. Endpoints in tests run on the server in the same way (and language) as they are run on the client.

**Comment by SandPod** [comment]
> However, I do want to point out that in my case, the database can't be mocked-out, because all my most important queries are unsafe/raw SQL queries.

Then this should align with your requirements. The tests depend on a running Postgres database instance that can be connected to using the development configuration and need to be run with concurrency 1.

The first line in main function creates a session with a connection to the database https://github.com/serverpod/serverpod/blob/6e43d86c4c8028acd932b20cdd022f9aa425de92/tests/serverpod_test_server/test_integration/column_operations/column_bool_test.dart#L20C1-L20C57.

Then that session is used to interact with the database.

**Comment by lukehutch** [comment]
@SandPod I'm picturing something more like a new Docker instance that is spun up before the unit tests are run, and is torn down afterwards. Something that runs on different ports from the development server. It needs to be a different instance so that unit tests don't screw up the data in the development server.

I actually start the development server in my code like this -- something similar could be set up as a standard test harness, complete with a matching teardown call:

```dart
import 'package:process_run/process_run.dart';

final shell = Shell();

/// Start local Docker instances (Postgres + Redis)
Future<void> startDocker() => shell.run('docker compose up --build --detach');
```

**Comment by SandPod** [comment]
OK!

Maybe we could take some inspiration from our postgress library, I think they do something like that: https://github.com/isoos/postgresql-dart/blob/master/test/docker.dart

Only thing we need to be mindful of is that Dart doesn't inherently keep track of its child processes and if we spawn a docker instance it might still be running if we abort the test: https://github.com/dart-lang/sdk/issues/49234

**Comment by iampopal** [comment]
We need to get a backup and restore using `pg_dump` and `pg_restore` on a Docker Postgres instance. How can we achieve this? any ideas or suggestions?

**Comment by lukehutch** [comment]
The easiest way is to run on GCP... All the backup management is integrated out of the box. (Not sure how to do it manually)

**Comment by hampuslavin** [comment]
The original issue reported here is now supported by the new test tools. Final PR merged here: https://github.com/serverpod/serverpod/pull/2882. See docs here on how to get started: https://docs.serverpod.dev/next/concepts/testing/get-started.
