### ISSUE TITLE
serverpod file upload 

### ISSUE THREAD

**Issue by hidayet-poscu** [serverpod/serverpod#2562]
When I use the Serverpod file upload module, it gives me a link like this: link='http://localhost:8080/serverpod_cloud_storage?method=file&path=a.jpg'. When I use this link with Image.network(link);, the file does not display. Also, when I type http://localhost:8080/serverpod_cloud_storage?method=file&path=a.jpg into the Chrome address bar, the file is not displayed.

Request URL:
http://localhost:8080/serverpod_cloud_storage?method=file&path=a.jpg
Request Method:
GET
Status Code:
404 Not Found
Remote Address:
[::1]:8080

**Comment by xyzbilal** [comment]
Hey @SandPod  I also have similar problem with getting public url or we do not understand exactly how to implement the logic. 

this function is endpoint function to store files in a folder and it creates folder an file under server folder with no problem. 

```
Future<String?> storeFile(Session session,{
  
    required String folder,
    required String filename,
    required ByteData byteData,
    DateTime? expiration,
    bool verified = true,
  }) async {
   
    try {
      var fullPath = 'uploads/$folder/$filename';

      print(fullPath);
      final buffer = byteData.buffer;
      final file =  File(fullPath);

      await file.create(recursive: true);
      
      file.writeAsBytes(

      buffer.asUint8List(byteData.offsetInBytes, byteData.lengthInBytes));
      final url = await getPublicUrl(session, fullPath);
      return url.toString();
    
    } catch (e) {
      throw Exception('Failed to store file. ($e)');
    }
  }

```


also retrieving file from client side is also with this function is also has no proplem

endpoint function


```
  Future<ByteData?> retrieveFile(Session session,{

    required String path,
  }) async {

    try {
      
      final file =File("uploads/$path");


      if (await file.exists()) {
        print("File exists");
        final ff = await file.readAsBytes();
        final f = ByteData.view(ff.buffer);
        return f;

      }
    } catch (e) {
      throw Exception('Failed to retrieve file. ($e)');
    }

    return null;
  }
```

in client side  calling  retrieveFile()  function works fine downloading file as ByteData ane converting it to file is also ok. 

The problem is when we try to make url public and try to get or show file directly using url  I cant  success.
I tried http://localhost:8080/uploads/file.pdf or http://localhost:8080/uploads/previews/file.png which are where I save files also is not useful for the purpose. 
Thanks for any kind of info.

**Comment by xyzbilal** [comment]
my problem was saving files to local directory of server instead of database. I created own files to solve the problem and its working fine.

I also created PR for it if someone else needs it. [PR](https://github.com/serverpod/serverpod/pull/2571)
