### ISSUE TITLE
Proper Serverpod CLI Development

### ISSUE THREAD

**Issue by AndryHTC** [serverpod/serverpod#2726]
**Describe the bug**
As noted in this comment https://github.com/serverpod/serverpod/discussions/2067#discussioncomment-10588583 you need to:
1. Change the code
2. Manually search for the Serverpod binary
3. Delete it
4. Run the Serverpod activate commands
5. Test the changes to the Serverpod CLI

**Expected behaviour**
1. After changing the code, running `dart pub global activate --source path tools/serverpod_cli` should trigger a rebuild of the CLI binary with the new changes.

**Platform information**
Windows, Mac OS

**Note**
To be noted, not even a `dart pub cache clean` fix this

**Comment by SandPod** [comment]
Unfortunately, this is not an issue with the Serverpod repo. You can create any dart CLI project and experience the same issue.

Please file this issue on the Dart repo instead.

**Comment by AndryHTC** [comment]
@SandPod Are you kidding? That doesn't make sense.

Why not creating a script that automatically does this?

And if that is true:
> create any dart CLI project and experience the same issue
At least

**Comment by SandPod** [comment]
This issue started just a couple of weeks ago and I'm guessing there is something wrong with a recent release of the Dart pub tooling.

The issue is tracked here: https://github.com/dart-lang/pub/issues/4295

We normally try and stay away from creating workarounds for real issues with the Dart tooling. You are free to create a script and post it here or in the forum if you get something working.
