### ISSUE TITLE
userCanEdit<field> not respect in the authentication module.

### ISSUE THREAD

**Issue by SandPod** [serverpod/serverpod#2746]
**Describe the bug**
The configuration in the authentication module allows a developer to define what a user is allowed to change.

However, these fields are not respected in the endpoints that modify the fields, allowing clients to modify the fields regardless of what this value is set to.

The fields can be found here: https://github.com/serverpod/serverpod/blob/70f26b6bf574b3e351b32f4bc9e956a166f1d8d8/modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart#L71-L77

**Expected behavior**
Setting any of these fields to false should disable the possibility to edit the fields on an endpoint in the server.

**Comment by dannejosefsson** [comment]
Some initial considerations and questions to take into account. Would love some feedback on these @SandPod 

* Checks for `userCanSee<field>` and `enableUserImages` are not implemented either. Are these also in scope? Or should we have a separate ticket for those? [enableUserImages]https://github.com/serverpod/serverpod/blob/70f26b6bf574b3e351b32f4bc9e956a166f1d8d8/modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart#L79-L86
* Given that https://github.com/serverpod/serverpod/blob/70f26b6bf574b3e351b32f4bc9e956a166f1d8d8/modules/serverpod_auth/serverpod_auth_server/lib/src/business/config.dart#L173  is the default value, is this considered a breaking change? I assume so at least.
* I guess the cleanest way is to implement the checks in the `Users` and `UserImages` classes and not in the corresponding endpoints. Do you agree?
* Since `AuthConfig.current` is used in a singelton manner, how should admin type of behaviour be taken into consideration? I guess the easiest way is to have an optional override flag or `AuthConfig` parameter in the method definitions.
* For the `userCanEditUserImage` checks, do you want them on the top level methods: `UserImage.setUserImage*`, on the low level method that actually does the update: `UserImage_setUserImage` or on both these for safety?
* Should we return `null`/`false` when the checks fail or should we `throw`? `UserImage` has an unused exception class defined, but `Users` doesn't.

**Comment by dannejosefsson** [comment]
@SandPod , any takes on my bullet list above?

**Comment by SandPod** [comment]
@dannejosefsson Sorry for the late reply on this.

> Checks for userCanSee<field> and enableUserImages...

I think these are out of scope for this issue, these are more used to modify client side configuration and are not connected to any rights of the user.

> is the default value, is this considered a breaking change?...

Since we recently introduced the endpoint that enabled the possibilty of changin the full name I don't believe this is used yet. I think it is fine to change this as a simple bugfix rather than a breaking change.

> I guess the cleanest way is to implement the checks in the...

Internally in the Server the developer should have rights to make any modificaitons without authentication. Therefore, I believe these checks should be implemented in the endpoints that are called from the client. Validating that "client" requests are authorized to perform the operations they request.

> Since AuthConfig.current is used in a singelton manner, how should admin type of behaviour be taken into consideration?....

N/A if implemented in the endpoint.

> For the userCanEditUserImage checks,....

N/A if implemented in the endpoint.

> Should we return `null`/`false` when the checks...

N/A if implemented in the endpoint.

**Comment by SandPod** [comment]
@dannejosefsson We will create a fix for this.
