### ISSUE TITLE
Respond with HTTP code 400 instead of 500 upon serializable exception

### ISSUE THREAD

**Issue by christerswahn** [serverpod/serverpod#2940]
**Describe the bug**
Currently Serverpod responds with HTTP code 500 when an endpoint method throws a serializable exception.

**Expected behavior**
Serverpod should respond with HTTP code 400 instead of 500 when an endpoint method throws a serializable exception.

**Comment by arpitgupta-it** [comment]
@christerswahn I've added the fix. Please see.

**Comment by arpitgupta-it** [comment]
@hampuslavin I've made the necessary changes. Could you please review?

**Comment by arpitgupta-it** [comment]
I've made changes, awaiting merge as lock approval from one of the reviewers. @hampuslavin

**Comment by hampuslavin** [comment]
@arpitgupta-it I think you just need to resign the CLA then we should be good to go!

**Comment by arpitgupta-it** [comment]
@hampuslavin there is no option to resign CLA as conversation is locked with no write access. Only a reviewer could do it.

**Comment by aho15** [comment]
I might be off as I just started with serverpod yesterday. However I think this issue is relevant again?
I have the exact same issue as described by @christerswahn.
When peeking into `serverpod-3.3.1\lib\src\server\server.dart` i found a comment which suggests this is expected behavior:
`
// Note: In case of malformed argument, the method connector may throw,
// which may be argued is not an "application space" exception.
` 

Is there some active decision towards this direction or an open discussion about this topic currently?

**Comment by marcelomendoncasoares** [comment]
> I might be off as I just started with serverpod yesterday. However I think this issue is relevant again? I have the exact same issue as described by [@christerswahn](https://github.com/christerswahn). When peeking into `serverpod-3.3.1\lib\src\server\server.dart` i found a comment which suggests this is expected behavior: `// Note: In case of malformed argument, the method connector may throw, // which may be argued is not an "application space" exception.`
> 
> Is there some active decision towards this direction or an open discussion about this topic currently?

Hi @aho15! This is not being discussed, as the issue was closed and we had no complaints of this happening again until now. Could you provide a bit more details on the requests that are generating the wrong status code for you?
