### ISSUE TITLE
Add hooks to auth module when a new user is created.

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#42]
Add a hooks for:
- When a user signs in through social logins. It should be possible to deny user account creation.
- When a user has been created to do additional steps of user setup.

**Comment by tp** [comment]
@vlidholt Am I correct in assuming that we tell what scopes we want, but then the user could still deny some of them?

I think for the core "should I accept this account hook" we should also present the scopes granted, so that the implementor can deny account creation if an essential capability has not been provided.

**Comment by vlidholt** [comment]
Added a new issue to track this: #46

**Comment by vlidholt** [comment]
Fixed
