### ISSUE TITLE
Support for spatial database

### ISSUE THREAD

**Issue by DvKyuth** [serverpod/serverpod#460]
Since the library is using Postgres as the database, Can we also have the option to enable PostGIS support? and add Geom datatype to the ORM?

**Comment by DvKyuth** [comment]
Thank you. Looking forward to it.

**Comment by lukehutch** [comment]
I need this too. It is enabled with

```sql
CREATE EXTENSION postgis;
```

then a column type would have to be added for lat/long data. The table is set up, and the column added, as follows:

https://postgis.net/docs/manual-3.4/using_postgis_dbmanagement.html#Create_Geography_Tables

Geography columns are used like this

https://postgis.net/docs/manual-3.4/using_postgis_dbmanagement.html#Use_Geography_Tables

You can set up spatial indexes:

https://postgis.net/docs/manual-3.4/using_postgis_dbmanagement.html#build-indexes

And then you can `ORDER BY` distance by using the `<->` operator:

https://postgis.net/docs/manual-3.4/reference.html#operators-distance

Personally I need only three things from spatial support:
1. Nearest neighbors (order by distance from a point)
2. The ability to calculate a distance between two points in m or km
3. The ability to index geography points, so that the nearest neighbor searches are fast

To support just this small number of things, I don't think it will require big changes to Serverpod.

**Comment by lukehutch** [comment]
Just wanted to point out that supporting `pgvector` is also very important for AI-powered applications, and it has very similar API needs to this. (See #1678)

**Comment by SandPod** [comment]
Draft implementation and source of inspiration: https://github.com/serverpod/serverpod/pull/1678.

If the above PR is used as inspiration for the implementation of this feature, the author @lukehutch should be credited as a co-author.

**Comment by lukehutch** [comment]
Just for the record, since I couldn't easily finish this implementation with the current Serverpod implementation, I built a geohash solution instead. It's very fast, although it's approximate.

**Comment by SandPod** [comment]
Ooh cool! Do you think it would be wrappable as a module?
