### ISSUE TITLE
CORS is NOT set to `Access-Control-Allow-Origin: *` if the endpoint fails

### ISSUE THREAD

**Issue by AndryHTC** [serverpod/serverpod#480]
By default the CORS is set to `Access-Control-Allow-Origin: *`, which should allow all origins.

_Originally posted by @vlidholt in https://github.com/serverpod/serverpod/discussions/82#discussioncomment-2126641_

But this does not happen when the endpoint throws an error.

**Comment by AndryHTC** [comment]
```
Access to XMLHttpRequest at 'http://localhost:8080/endpoint' from origin 'http://localhost:57215' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

js_primitives.dart:30 ServerpodClientException: Unknown server response code. (XMLHttpRequest error.), statusCode = -1 browser_client.dart:72 POST http://localhost:8080/endpoint net::ERR_FAILED 500
```

**Comment by yahu1031** [comment]
Is there something that we need to set `SecurityContext`?

**Comment by AndryHTC** [comment]
> 

Sorry, I don't understand what are you referring to

**Comment by yahu1031** [comment]
As I remember, This [SecurityContext](https://api.flutter.dev/flutter/dart-io/SecurityContext-class.html) fixed the CORS issue.

**Comment by vlidholt** [comment]
I will look into this.

**Comment by chetanxpatil** [comment]
Cross-Origin Resource Sharing (CORS) is a security feature implemented by web browsers that prevents a web page from making requests to a different domain than the one that served the web page. When a web page makes a request to a different domain, the browser sends an HTTP request header called "Origin" to the server, along with the request. The server can then either allow or deny the request based on the value of the "Origin" header.

If a server is configured to set the "Access-Control-Allow-Origin" header to "", it is indicating that it allows any domain to make requests to it. If the server is not configured to set this header to "" or to the domain of the requesting page, the browser will block the request and the page will not be able to access the server's resources.

If you are trying to make a request to a server and it is failing because the "Access-Control-Allow-Origin" header is not set to "*", it means that the server is not allowing your domain to make requests to it. In this case, you will need to either modify the server's configuration to allow your domain to make requests, or you will need to make the request from a domain that is allowed by the server.

**Comment by AndryHTC** [comment]
@chetanxpatil thank you for the contribution. You may read again the issue, I'm not issuing about CORS

**Comment by DarioTheLuca** [comment]
![480](https://user-images.githubusercontent.com/102025882/209486912-5c080903-adfb-4086-bf77-641135c6e54c.jpg)

As shown in the image, the `Access-Control-Allow-Origin: *` is added only if ( result is ResultSuccess ) , so i suppose if the result is an exception, this header isn't added.

**Comment by AndryHTC** [comment]
@DarioTheLuca, thank you for the investigation. This will help @vlidholt. I think it is an unexpected behavior that should be fixed. But let's wait for the boss's decision 😄

**Comment by vlidholt** [comment]
Fixed.
