### ISSUE TITLE
Password written in plaintext to logs?

### ISSUE THREAD

**Issue by vsaase** [serverpod/serverpod#629]
https://github.com/serverpod/serverpod/blob/e137cac2550d8df3d16f404894ea5627d59c9f93/modules/serverpod_auth/serverpod_auth_server/lib/src/endpoints/email_endpoint.dart#L22

Am I missing something or is this a big security issue?
I think it would also be good to do password hashing on the client side.

**Comment by fischerscode** [comment]
As far, as I know, it's common practice to hash the password at the server side.
<details>
<summary>Google does it...</summary>
Sign in to Google with the wrong password and have a look at the send messages...

![grafik](https://user-images.githubusercontent.com/45403027/217606511-df2efd2c-4444-4255-937a-680d8ecec81d.png)
</details>

It might be safe to hash the password at the client side and then treat the hash like a password on the server side. But this makes it impossible to ensure the password is secure enough at the server side. And, unless it's opt-in (for the developer), this would be a breaking change.

Personally I'm looking forward to something like [opaque](https://datatracker.ietf.org/doc/draft-irtf-cfrg-opaque/).

However... I think it would be better to make sure the password is never logged.

**Comment by fleeser** [comment]
I think there is a bit of a misunderstanding here:

Inside of the `Session` class, you can find the following:

```
if (serverpod.runMode == ServerpodRunMode.development) {
  stdout.writeln('${entry.logLevel.name.toUpperCase()}: ${entry.message}');
  if (entry.error != null) stdout.writeln(entry.error);
  if (entry.stackTrace != null) stdout.writeln(entry.stackTrace);
}
```

This means that the logs are only logged if their `LogLevel` matches the current `RunMode`. If the developers are doing a debug run, there is no need for hiding the password. Maybe they even want to see the password to check if it matches their expectations when testing the hashing procedure for example.

The Logs are also saved to the database by default to have a look at them later on, but this is also secured by the following lines of code:

```
if (!serverpod.logManager.shouldLogEntry(session: this, entry: entry)) {
  return;
}

bool shouldLogEntry({
  required Session session,
  required LogEntry entry,
}) {
  var logSettings = getLogSettingsForSession(session);
  var serverLogLevel = (logSettings.logLevel);
  
  return entry.logLevel.index >= serverLogLevel.index;
}
```

This means an entry is only created when "it should". In production debug logs won't be saved.

**Comment by vsaase** [comment]
ok fine
Still I think running the server in debug mode with users who are not aware of the password logging can happen.
Some users use the same passwords for many sites, you don't want to accidentally see those passwords on your screen or in your logs.

**Comment by fleeser** [comment]
@vsaase As stated in my answer before there is no security problem with this approach of logging passwords since this is exactly how other big companies log their data to the console. When running in debug mode, only developers can see the logs. If a developer uses one of his private passwords, which would be the situation you are talking about I guess, it would be the problem of the developer. I think every developer knows about this.

**Comment by vlidholt** [comment]
Not an issue if you run Serverpod with the default setup, but this should be fixed. Either by removing the log altogether or by masking out the password part.

**Comment by ramyak-mehra** [comment]
Not really, I don't think so Django does it this way, you should never log real passwords not in any mode, as soon as password arrives it should be hashed with a private key. there is no relevance for a developer to see the passwords even in the debug mode, he can be sure he put the right password because the hash would be same everytime, and he can't get the password from hash but can get the hash from password
