### ISSUE TITLE
Support for inheritance in protocol/*.yaml files

### ISSUE THREAD

**Issue by kieran-myopnotes** [serverpod/serverpod#793]
**Is your feature request related to a problem? Please describe.**
The problem with the lack of support for inheritance is that this is the only thing that dart does not provide a workaround for. If you wish to add functions or setters/getters to a generated object then you can simply extend that class which is a built in feature of dart. However, there is currently nothing you can do if you wish to have one of your serverpod classes inherit another one of your serverpod classes to achieve things like polymorphism. 

**Describe the solution you'd like**
Similar to the way you specify the "class: ClassName" and the "table: table_name", there should be a third option for "inherits: InheritedClassName" 

**Describe alternatives you've considered**
alternatively, you could follow the standard dart naming convention and use "extends: InheritedClassName". This would allow for future additions for the "implements: InterfaceClassName" and "with: MixinClass1, MixinClass2, MixinClass3". Although in order for these to work you would need a way in your serverpod object to specify the class type and whether it is a Class, Interface, or Mixin

**Additional context**
This has been the single largest issue for me and my dev team as we use serverpod in our production application with the only alternative being to manually define classes and use the freezed package however we wish to continue using the simple syntax provided by serverpod.

**Comment by wstrange** [comment]
This underscores one of the issues with using yaml to generate Dart, instead of just using native Dart + annotations. 

Older discussion but still relevant: https://github.com/serverpod/serverpod/discussions/186

**Comment by tgrushka** [comment]
I wan to use message streaming to notify my clients of updates to models. The following code compiles, and the endpoint sends the message, but the clients never receive it, because the deserialization gets messed up.

I spent hours trying to figure out why messages weren't being received, then when I removed the `entity` field, everything worked fine.

This is all because inheritance is not supported. Why can't I even use `SerializableEntity` as a generic type so my `entity` can be dynamic?

(Also, the `serverpod:ModelClass` thing is totally undocumented, I discovered it by accident.)

```yaml
class: UpdateMessage
fields:
  user: module:auth:UserInfo
  action: UpdateAction
  entity: serverpod:SerializableEntity
```

**Comment by Isakdl** [comment]
@tgrushka I think what you are asking for here is different from inheritance on the classes them self's. 

You want to use a base model of a type so that you can add the classes that extends the base model. I think this will more or less be impossible to resolve as we will not know the type we need to serialize / de-serialize into, as I presume you actually want the full class not just the base one defined here. 

However I think the solution here is to support Generic types, where you could define something like this:

```yaml
class: UpdateMessage<T>
fields:
  user: module:auth:UserInfo
  action: UpdateAction
  entity: T
```

Then we should be able to embed enough information in the message to resolve the datatype, related discussion here: https://github.com/serverpod/serverpod/issues/1035.

**Comment by SandPod** [comment]
Closing this issue and will reference the discussion from the RFC for model inheritance here: https://github.com/serverpod/serverpod/issues/1873
