### ISSUE TITLE
-f option bug (feat. podman)

### ISSUE THREAD

**Issue by sadobass** [serverpod/serverpod#864]
**Describe the bug**
The database name is generated differently when running with the -f option.

**To Reproduce**
1. Use podman instead docker (feat alias setting : alias docker=podman, alias docker-compose=podman-compose )
2. Run serverpod create -f mydemopod (It will not work without the -f option)
3. cd mydemopod/mydemopod_server
4. docker-compose up --build --detach
5. See log ".... com.docker.compose.service=postgres -e POSTGRES_USER=postgres -e **POSTGRES_DB=mydemopod** ...."
6. The database was created with "**postgres**".

**Expected behavior**
The database must be created with "**mydemopod**".

**Screenshots**
![스크린샷 2023-05-03 오전 9 58 24](https://user-images.githubusercontent.com/5369741/235815312-51ff5d22-f484-4a51-98a8-9e74858a234a.png)
![스크린샷 2023-05-03 오전 9 53 58](https://user-images.githubusercontent.com/5369741/235815321-3239ed33-5d29-47f4-a590-bbf8426a0ee2.png)

**Serverpod versions**
 -  _CLI Version: 1.1.0
 - _Library version: serverpod: ^1.1.0

**Platform information**
macOS 13.3.1

**Comment by vlidholt** [comment]
We don't really have support for podman, but it may be a good idea to add it for the future.

**Comment by yahu1031** [comment]
@sadobass There was already a ticket/discussion on this. And also If docker and podman are both installed, then this won't work because of the config conflicts.

When you alias it, the serverpod cli considers it as docker and it doesn't know it was podman machine. So when we are checking docker is running, We are spawning a process of the `docker info` command. which internally runs `podman info` and it gives

```console
Error: failed to connect: dial tcp [::1]:56858: connect: connection refused
```

So when this happens, you will be seeing the

```console
There are some issues with your setup that will prevent your Serverpod project
from running out of the box and without further configuration. You can still
create this project by passing -f to "serverpod create" and manually configure
your Serverpod.

You do not have Docker installed or it is not running. Serverpod uses Docker to
run Postgres and Redis. It's recommended that you install Docker Desktop from
https://www.docker.com/get-started but you can also install and configure
Postgres and Redis manually and run this command with the -f flag added.
```

message.

And @vlidholt this better not go into enhancement as of now, at least this ticket better neither be marked as an enhancement request nor a bug. Cause all these env setups were done by the user but not by the serverpod CLI.

And as the user doesn't provide the required env to the serverpod, it does return the correct response.

But yes, Having this kind of support is also important.

**Comment by SandPod** [comment]
We no longer required postgres to be installed to create a project, and the new migration system is agnostic to the database runtime environment. So this should no longer be an issue.
