### ISSUE TITLE
Serialize enums as a string instead of number

### ISSUE THREAD

**Issue by vlidholt** [serverpod/serverpod#885]
### Discussed in https://github.com/serverpod/serverpod/discussions/879

<div type='discussions-op-text'>

<sup>Originally posted by **andriyndev** May  6, 2023</sup>
(Copy-pasted from https://github.com/serverpod/serverpod/discussions/715 because it's a separate issue)

I think enum's values should never be serialized by numeric values because if the app's developer edits the enum so that the values of the current elements are shifted, it'll cause nasty consequences. For example, user selects one value, but it's written to the database as another one, and the worse is that they'll see it as they specified it while other users with more recent versions of the app will see it as it was written to the database. It might be especially dangerous if the data represents delicate information like user's religion, political view, sexual orientation, gender etc. And even if the app's developers are aware of this nuance, they still might be susceptible to human factor. And if the mistake will be made, it might be impossible to fix the consequences without interacting with each user who triggered writes of the data to the database because there is no way for the app's developers to know whether the value is what the user actually selected.</div>

**Comment by lukehutch** [comment]
Since `toString()` can be overridden now in Dart enums, probably the `toString` value can be written to the database.

A `serverpod generate` test can run through the enum's values, checking that all the `toString` values are unique, and then an invertible map can be created mapping from values to strings, and strings to values.

To make this backwards-compatible, the database column type can be checked -- if it's int-typed, then the old (positional) scheme can be used; if it's string-typed, then the new `toString` mapping can be used.

**Comment by lukehutch** [comment]
Please see PR #1080.

**Comment by lukehutch** [comment]
Re @tgrushka's [comment](https://github.com/serverpod/serverpod/discussions/879#discussioncomment-5827108) about supporting custom serialization: I originally modified the yaml parser to support a custom serialization value, e.g.

`  - active serialize='A'`

but then I ran into an issue with this approach. Specifically, `packages/serverpod/lib/src/database/expressions.dart` contains the query syntax code, and it defines the class `class ColumnEnum<E extends Enum> extends Column`. Since this is a generic `Enum`, any additional value (such as the serialized value) is not available to the methods of this class, without ugly casting, or the use of an external dictionary.

Consequently, I opted for simply serializing to the enum values' `name`. Anyway this is the most predictable way to serialize an enum constant.

The enum value names may be too long for some usecases. I would prefer enums to be serialized as a single letter, to save on database storage. I could probably just use enum constants like `A` rather than `active`, then explain in the documentation comment what `A` actually means (so that the explanation pops up in an IDE).

**Comment by tgrushka** [comment]
Thanks @lukehutch! Just dealing with this now. Let's say I have the following enum, so serializing by only first letter would not work (but to me it is totally fine to use the `.name` value in the database, which might even be possible to address/catch in the migration process if changed as well):
```yaml
enum: PlatformType
values:
  - androidCTV
  - androidMobile
  - appleIOS
  - appleTVOS
  - roku
  - webBrowser
  - webCTV
```

**Comment by tgrushka** [comment]
^^ Ha! I guess the strict lowerCamelCase is a good thing for this as well, which seems a bit funky with some of the names but will help prevent simple user error like changing the case of a value and having it break the database:

```
Error on line 3, column 5 of lib/src/protocol/platform_type.yaml: Enum values must be lowerCamelCase.
  ╷
3 │   - androidCTV
  │     ^^^^^^^^^^
  ╵
```

**Comment by lukehutch** [comment]
Right, using just one letter was just my requirement for keeping data size small. In gernwral using name is the right thing to do. (My patch does that.)

I ran into the camel case requirement for enum constants `Gender.M` and `Gender.F`... I think that should be a warning at worst, not an error!

**Comment by lukehutch** [comment]
Updated PR in #1518.
